[package]
name = "sweep-scan"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true

[dependencies]
blake3.workspace = true
ignore.workspace = true
rayon.workspace = true
sweep-core.workspace = true

[dev-dependencies]
tempfile.workspace = true
