[package]
name = "sweep-tui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true

[dependencies]
ratatui.workspace = true
sweep-report.workspace = true
sweep-scan.workspace = true
tachyonfx.workspace = true
