use std::path::Path;

use sweep_core::{CandidateKind, RecoveryContract, RecoveryKind};

use super::{GitEvidencePolicy, Provider, ProviderAssessment, ProviderContext};

pub struct NodeProvider;

impl Provider for NodeProvider {
    fn assess(&self, path: &Path, _context: &ProviderContext) -> Option<ProviderAssessment> {
        let name = path.file_name()?.to_str()?;
        let parent = path.parent()?;

        if !parent.join("package.json").is_file() {
            return None;
        }

        match name {
            "node_modules" => Some(node_modules(parent)),
            ".next" => Some(ProviderAssessment::new(
                CandidateKind::NextBuild,
                RecoveryContract {
                    kind: RecoveryKind::Rebuild,
                    command: build_command(parent),
                    detail: String::from(
                        "Next.js build output is reproducible from project sources.",
                    ),
                },
                GitEvidencePolicy::Required,
                "package.json + .next",
            )),
            ".turbo" => Some(ProviderAssessment::new(
                CandidateKind::TurboCache,
                RecoveryContract {
                    kind: RecoveryKind::Rebuild,
                    command: Some(String::from("turbo run <task>")),
                    detail: String::from("Turborepo local cache is generated by task execution."),
                },
                GitEvidencePolicy::Required,
                "package.json + .turbo",
            )),
            _ => None,
        }
    }
}

fn node_modules(parent: &Path) -> ProviderAssessment {
    let restore = dependency_restore(parent);
    let mut assessment = ProviderAssessment::new(
        CandidateKind::NodeModules,
        RecoveryContract {
            kind: RecoveryKind::ReinstallDependencies,
            command: restore.as_ref().map(|(_, command)| command.clone()),
            detail: String::from(
                "Dependencies are reconstructable when a supported lockfile defines the install boundary.",
            ),
        },
        GitEvidencePolicy::Required,
        "package.json + node_modules",
    );

    if let Some((lockfile, _)) = restore {
        assessment.prove(
            "dependency_lockfile",
            format!("Supported dependency lockfile present: {lockfile}."),
        );
    } else {
        assessment.review(
            "dependency_lockfile",
            "No supported dependency lockfile was found; exact dependency recovery is not proven.",
        );
    }

    assessment
}

fn dependency_restore(parent: &Path) -> Option<(&'static str, String)> {
    if parent.join("pnpm-lock.yaml").is_file() {
        return Some((
            "pnpm-lock.yaml",
            String::from("pnpm install --frozen-lockfile"),
        ));
    }

    if parent.join("yarn.lock").is_file() {
        let command = if parent.join(".yarnrc.yml").is_file() {
            "yarn install --immutable"
        } else {
            "yarn install --frozen-lockfile"
        };
        return Some(("yarn.lock", String::from(command)));
    }

    if parent.join("package-lock.json").is_file() {
        return Some(("package-lock.json", String::from("npm ci")));
    }

    None
}

fn build_command(parent: &Path) -> Option<String> {
    if parent.join("pnpm-lock.yaml").is_file() {
        return Some(String::from("pnpm build"));
    }

    if parent.join("yarn.lock").is_file() {
        return Some(String::from("yarn build"));
    }

    if parent.join("package-lock.json").is_file() {
        return Some(String::from("npm run build"));
    }

    None
}

#[cfg(test)]
mod tests {
    use std::fs;

    use sweep_core::Decision;
    use tempfile::tempdir;

    use super::*;

    #[test]
    fn node_modules_requires_supported_lockfile_for_safe_provider_assessment() {
        let root = tempdir().unwrap();
        fs::write(root.path().join("package.json"), "{}").unwrap();
        fs::create_dir(root.path().join("node_modules")).unwrap();

        let assessment = NodeProvider
            .assess(
                &root.path().join("node_modules"),
                &ProviderContext { home: None },
            )
            .unwrap();

        assert_eq!(assessment.decision, Decision::Review);
    }

    #[test]
    fn package_lock_provides_npm_ci_recovery_contract() {
        let root = tempdir().unwrap();
        fs::write(root.path().join("package.json"), "{}").unwrap();
        fs::write(root.path().join("package-lock.json"), "{}").unwrap();
        fs::create_dir(root.path().join("node_modules")).unwrap();

        let assessment = NodeProvider
            .assess(
                &root.path().join("node_modules"),
                &ProviderContext { home: None },
            )
            .unwrap();

        assert_eq!(assessment.decision, Decision::Safe);
        assert_eq!(assessment.recovery.command.as_deref(), Some("npm ci"));
    }
}
