use std::path::{Path, PathBuf};

use sweep_core::{CandidateKind, RecoveryContract, RecoveryKind};

use super::{GitEvidencePolicy, Provider, ProviderAssessment, ProviderContext};

pub struct NodeProvider;

impl Provider for NodeProvider {
    fn assess(&self, path: &Path, _context: &ProviderContext) -> Option<ProviderAssessment> {
        let name = path.file_name()?.to_str()?;
        let parent = path.parent()?;

        if !parent.join("package.json").is_file() {
            return None;
        }

        match name {
            "node_modules" => Some(node_modules(parent)),
            ".next" => Some(ProviderAssessment::new(
                CandidateKind::NextBuild,
                RecoveryContract {
                    kind: RecoveryKind::Rebuild,
                    command: build_command(parent),
                    detail: String::from(
                        "Next.js build output is reproducible from project sources.",
                    ),
                },
                GitEvidencePolicy::Required,
                "package.json + .next",
            )),
            ".turbo" => Some(ProviderAssessment::new(
                CandidateKind::TurboCache,
                RecoveryContract {
                    kind: RecoveryKind::Rebuild,
                    command: Some(String::from("turbo run <task>")),
                    detail: String::from("Turborepo local cache is generated by task execution."),
                },
                GitEvidencePolicy::Required,
                "package.json + .turbo",
            )),
            _ => None,
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum PackageManager {
    Pnpm,
    Yarn,
    Npm,
    Bun,
}

#[derive(Clone, Debug, Eq, PartialEq)]
struct DependencyRestore {
    manager: PackageManager,
    lockfile: &'static str,
    root: PathBuf,
    command: String,
}

fn node_modules(parent: &Path) -> ProviderAssessment {
    let restore = dependency_restore(parent);
    let mut assessment = ProviderAssessment::new(
        CandidateKind::NodeModules,
        RecoveryContract {
            kind: RecoveryKind::ReinstallDependencies,
            command: restore.as_ref().map(|restore| restore.command.clone()),
            detail: String::from(
                "Dependencies are reconstructable when a supported lockfile defines the install boundary.",
            ),
        },
        GitEvidencePolicy::Required,
        "package.json + node_modules",
    );

    if let Some(restore) = restore {
        if restore.root == parent {
            assessment.prove(
                "dependency_lockfile",
                format!("Supported dependency lockfile present: {}.", restore.lockfile),
            );
        } else {
            assessment.prove(
                "dependency_lockfile",
                format!(
                    "Supported dependency lockfile inherited from an ancestor repository scope: {}.",
                    restore.lockfile
                ),
            );
        }
    } else {
        assessment.review(
            "dependency_lockfile",
            "No supported dependency lockfile was found within the candidate's repository scope; exact dependency recovery is not proven.",
        );
    }

    assessment
}

fn dependency_restore(parent: &Path) -> Option<DependencyRestore> {
    let repository_root = repository_root(parent);
    let mut current = Some(parent);

    while let Some(directory) = current {
        if let Some(restore) = dependency_restore_at(directory) {
            return Some(restore);
        }

        if repository_root.as_deref() == Some(directory) || repository_root.is_none() {
            break;
        }

        current = directory.parent();
    }

    None
}

fn dependency_restore_at(directory: &Path) -> Option<DependencyRestore> {
    if directory.join("pnpm-lock.yaml").is_file() {
        return Some(DependencyRestore {
            manager: PackageManager::Pnpm,
            lockfile: "pnpm-lock.yaml",
            root: directory.to_path_buf(),
            command: String::from("pnpm install --frozen-lockfile"),
        });
    }

    if directory.join("yarn.lock").is_file() {
        let command = if directory.join(".yarnrc.yml").is_file() {
            "yarn install --immutable"
        } else {
            "yarn install --frozen-lockfile"
        };

        return Some(DependencyRestore {
            manager: PackageManager::Yarn,
            lockfile: "yarn.lock",
            root: directory.to_path_buf(),
            command: String::from(command),
        });
    }

    if directory.join("package-lock.json").is_file() {
        return Some(DependencyRestore {
            manager: PackageManager::Npm,
            lockfile: "package-lock.json",
            root: directory.to_path_buf(),
            command: String::from("npm ci"),
        });
    }

    if directory.join("bun.lock").is_file() {
        return Some(DependencyRestore {
            manager: PackageManager::Bun,
            lockfile: "bun.lock",
            root: directory.to_path_buf(),
            command: String::from("bun install --frozen-lockfile"),
        });
    }

    if directory.join("bun.lockb").is_file() {
        return Some(DependencyRestore {
            manager: PackageManager::Bun,
            lockfile: "bun.lockb",
            root: directory.to_path_buf(),
            command: String::from("bun install --frozen-lockfile"),
        });
    }

    None
}

fn repository_root(start: &Path) -> Option<PathBuf> {
    start
        .ancestors()
        .find(|ancestor| {
            let git = ancestor.join(".git");
            git.is_dir() || git.is_file()
        })
        .map(Path::to_path_buf)
}

fn build_command(parent: &Path) -> Option<String> {
    let restore = dependency_restore(parent)?;

    Some(match restore.manager {
        PackageManager::Pnpm => String::from("pnpm build"),
        PackageManager::Yarn => String::from("yarn build"),
        PackageManager::Npm => String::from("npm run build"),
        PackageManager::Bun => String::from("bun run build"),
    })
}

#[cfg(test)]
mod tests {
    use std::fs;

    use sweep_core::Decision;
    use tempfile::tempdir;

    use super::*;

    #[test]
    fn node_modules_requires_supported_lockfile_for_safe_provider_assessment() {
        let root = tempdir().unwrap();
        fs::write(root.path().join("package.json"), "{}").unwrap();
        fs::create_dir(root.path().join("node_modules")).unwrap();

        let assessment = NodeProvider
            .assess(
                &root.path().join("node_modules"),
                &ProviderContext { home: None },
            )
            .unwrap();

        assert_eq!(assessment.decision, Decision::Review);
    }

    #[test]
    fn package_lock_provides_npm_ci_recovery_contract() {
        let root = tempdir().unwrap();
        fs::write(root.path().join("package.json"), "{}").unwrap();
        fs::write(root.path().join("package-lock.json"), "{}").unwrap();
        fs::create_dir(root.path().join("node_modules")).unwrap();

        let assessment = NodeProvider
            .assess(
                &root.path().join("node_modules"),
                &ProviderContext { home: None },
            )
            .unwrap();

        assert_eq!(assessment.decision, Decision::Safe);
        assert_eq!(assessment.recovery.command.as_deref(), Some("npm ci"));
    }

    #[test]
    fn workspace_package_inherits_repository_lockfile() {
        let root = tempdir().unwrap();
        fs::create_dir(root.path().join(".git")).unwrap();
        fs::write(root.path().join("pnpm-lock.yaml"), "lockfileVersion: '9.0'\n").unwrap();

        let package = root.path().join("packages/ui");
        fs::create_dir_all(package.join("node_modules")).unwrap();
        fs::write(package.join("package.json"), "{}").unwrap();

        let assessment = NodeProvider
            .assess(
                &package.join("node_modules"),
                &ProviderContext { home: None },
            )
            .unwrap();

        assert_eq!(assessment.decision, Decision::Safe);
        assert_eq!(
            assessment.recovery.command.as_deref(),
            Some("pnpm install --frozen-lockfile")
        );
        assert!(assessment.evidence.iter().any(|evidence| {
            evidence.code == "dependency_lockfile"
                && evidence.detail.contains("ancestor repository scope")
        }));
    }

    #[test]
    fn lockfile_search_does_not_escape_repository_boundary() {
        let root = tempdir().unwrap();
        fs::write(root.path().join("pnpm-lock.yaml"), "lockfileVersion: '9.0'\n").unwrap();

        let repository = root.path().join("repo");
        fs::create_dir_all(repository.join(".git")).unwrap();

        let package = repository.join("packages/ui");
        fs::create_dir_all(package.join("node_modules")).unwrap();
        fs::write(package.join("package.json"), "{}").unwrap();

        let assessment = NodeProvider
            .assess(
                &package.join("node_modules"),
                &ProviderContext { home: None },
            )
            .unwrap();

        assert_eq!(assessment.decision, Decision::Review);
    }

    #[test]
    fn bun_lock_provides_frozen_install_recovery_contract() {
        let root = tempdir().unwrap();
        fs::write(root.path().join("package.json"), "{}").unwrap();
        fs::write(root.path().join("bun.lock"), "").unwrap();
        fs::create_dir(root.path().join("node_modules")).unwrap();

        let assessment = NodeProvider
            .assess(
                &root.path().join("node_modules"),
                &ProviderContext { home: None },
            )
            .unwrap();

        assert_eq!(assessment.decision, Decision::Safe);
        assert_eq!(
            assessment.recovery.command.as_deref(),
            Some("bun install --frozen-lockfile")
        );
    }
}
