use std::path::Path;

use sweep_core::{CandidateKind, RecoveryContract, RecoveryKind};

use super::{GitEvidencePolicy, Provider, ProviderAssessment, ProviderContext};

pub struct XcodeProvider;

impl Provider for XcodeProvider {
    fn assess(&self, path: &Path, context: &ProviderContext) -> Option<ProviderAssessment> {
        let home = context.home()?;
        let root = home.join("Library/Developer/Xcode/DerivedData");

        if path.parent()? != root {
            return None;
        }

        Some(ProviderAssessment::new(
            CandidateKind::XcodeDerivedData,
            RecoveryContract {
                kind: RecoveryKind::IdeRegeneration,
                command: None,
                detail: String::from("Xcode DerivedData is regenerated by Xcode/build tooling."),
            },
            GitEvidencePolicy::NotApplicable,
            "~/Library/Developer/Xcode/DerivedData/<entry>",
        ))
    }
}

#[cfg(test)]
mod tests {
    use std::path::PathBuf;

    use super::*;

    #[test]
    fn derived_data_entry_does_not_require_git_ownership() {
        let home = PathBuf::from("/Users/example");
        let context = ProviderContext {
            home: Some(home.clone()),
        };
        let path = home.join("Library/Developer/Xcode/DerivedData/App-ABC123");

        let assessment = XcodeProvider.assess(&path, &context).unwrap();

        assert_eq!(assessment.git_evidence, GitEvidencePolicy::NotApplicable);
    }
}
