use std::path::Path;

use sweep_core::{CandidateKind, RecoveryContract, RecoveryKind};

use super::{GitEvidencePolicy, Provider, ProviderAssessment, ProviderContext};

pub struct ZigProvider;

impl Provider for ZigProvider {
    fn assess(&self, path: &Path, _context: &ProviderContext) -> Option<ProviderAssessment> {
        let name = path.file_name()?.to_str()?;
        let parent = path.parent()?;

        if !parent.join("build.zig").is_file() {
            return None;
        }

        let kind = match name {
            ".zig-cache" => CandidateKind::ZigCache,
            "zig-out" => CandidateKind::ZigOutput,
            _ => return None,
        };

        Some(ProviderAssessment::new(
            kind,
            RecoveryContract {
                kind: RecoveryKind::Rebuild,
                command: Some(String::from("zig build")),
                detail: String::from("Zig build state is regenerated by the project build."),
            },
            GitEvidencePolicy::Required,
            format!("build.zig + {name}"),
        ))
    }
}

#[cfg(test)]
mod tests {
    use std::fs;

    use tempfile::tempdir;

    use super::*;

    #[test]
    fn zig_cache_requires_build_zig_boundary() {
        let root = tempdir().unwrap();
        fs::create_dir(root.path().join(".zig-cache")).unwrap();

        assert!(
            ZigProvider
                .assess(
                    &root.path().join(".zig-cache"),
                    &ProviderContext { home: None },
                )
                .is_none()
        );

        fs::write(root.path().join("build.zig"), "").unwrap();

        assert!(
            ZigProvider
                .assess(
                    &root.path().join(".zig-cache"),
                    &ProviderContext { home: None },
                )
                .is_some()
        );
    }
}
